# Generated by Django 4.0.5 on 2022-08-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_roles',
            old_name='roles_id',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='user_roles',
            old_name='user_id',
            new_name='user',
        ),
    ]
