# Generated by Django 4.0.5 on 2022-08-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='incategories',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='incategories',
            old_name='categories_id',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
